#!/bin/sh
# Writes .env: the password for the reviewer's account and the port the stack publishes. The password is
# 24 random alphanumeric characters (~143 bits), generated here, printed once, and never committed
# (.gitignore). The host image's /etc/passwd holds its hash; the plaintext is also in the image's build
# history on this machine (docker-compose.yml).
set -eu

here=$(cd "$(dirname "$0")" && pwd)
cd "$here"

case "${1:-}" in
'') ;;
--force) ;;
*)
  echo "usage: $0 [--force]" >&2
  exit 2
  ;;
esac

if [ -f .env ] && [ "${1:-}" != "--force" ]; then
  echo ".env already exists; keeping it. Run $0 --force to generate a new password (the container must be" >&2
  echo "rebuilt then: ./up.sh)." >&2
  exit 0
fi

password=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24 || true)
if [ "${#password}" -ne 24 ]; then
  echo "cannot read /dev/urandom" >&2
  exit 1
fi

port=${REVIEW_SSH_PORT:-22222}
case $port in
'' | *[!0-9]*)
  echo "REVIEW_SSH_PORT must be a number: $port" >&2
  exit 2
  ;;
esac

umask 077
cat >.env <<EOF
# Generated by setup.sh (store/review-demo). Gitignored: never commit it. Delete it and run setup.sh
# again for a new password, then rebuild with ./up.sh.
REVIEW_PASSWORD=$password
REVIEW_SSH_PORT=$port
EOF

echo "review demo credentials (printed once, also in $here/.env):"
echo "  user:     review"
echo "  password: $password"
echo "  ssh port: $port"
echo
echo "Next: ./up.sh — it builds the images, starts the stack and prints the address and the values to"
echo "paste into App Store Connect and the Play Console."
