#!/bin/sh
# Builds and starts the review demo, then prints the address and the credentials to paste into App Store
# Connect and the Play Console. Re-run it after changing anything here: the reviewer's home, their
# sessions and the host keys live in the volume and survive.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
cd "$here"

if [ ! -f .env ]; then
  echo "no .env: run ./setup.sh first (it generates the reviewer's password)" >&2
  exit 1
fi

# shellcheck source=/dev/null  # .env is generated by setup.sh
. ./.env
port=${REVIEW_SSH_PORT:-22222}

docker compose --env-file .env up -d --build

# sshd answers after omp is not needed: the reviewer connects minutes or hours later. Wait for its banner
# so the printed block is usable right away.
if command -v ssh-keyscan >/dev/null 2>&1; then
  tries=0
  until ssh-keyscan -T 2 -p "$port" 127.0.0.1 >/dev/null 2>&1; do
    tries=$((tries + 1))
    if [ "$tries" -ge 60 ]; then
      docker compose --env-file .env logs --tail 40 host >&2
      echo "sshd did not answer on 127.0.0.1:$port" >&2
      exit 1
    fi
    sleep 1
  done
else
  echo "(ssh-keyscan is not installed; not waiting for sshd)" >&2
  sleep 3
fi

addresses=$(hostname -I 2>/dev/null || true)
[ -n "$addresses" ] || addresses=$(ip -4 -o addr show scope global 2>/dev/null | awk '{ print $4 }' | cut -d/ -f1 | tr '\n' ' ' || true)

echo
echo "ompanion review demo is up."
echo
echo "Add this machine in the app — App Store Connect: App Review Information (sign-in required);"
echo "Play Console: App access. The values:"
echo "  host:     the public address of this server"
[ -n "$addresses" ] && echo "            (this server: $addresses)"
echo "  port:     $port"
echo "  user:     review"
echo "  password: $(sed -n 's/^REVIEW_PASSWORD=//p' .env)"
echo "  auth:     Password  (the app's machine editor calls the field Authentication)"
echo
echo "Host key the app asks to trust:"
docker compose --env-file .env exec -T host ssh-keygen -lf /data/ssh/ssh_host_ed25519_key.pub
echo
echo "Firewall: allow only $port from the internet. Everything else on this VPS can stay closed."
echo "After the review:"
echo "  ./reset.sh       put the reviewer's home back (they may have edited files)"
echo "  ./down.sh --clean   stop the stack and delete the reviewer's home and the host keys"
