#!/usr/bin/env bash
# Regenerates every app icon and the README logo from assets/ompanion.svg (the full icon) and
# assets/ompanion_glyph.svg (the π alone, same canvas and position). Output is byte-identical across
# runs. The Apple icons are Icon Composer bundles in macos/ and ios/; their layer is the glyph SVG.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"

icon_svg=assets/ompanion.svg
glyph_svg=assets/ompanion_glyph.svg
android_res=android/app/src/main/res

if ! command -v rsvg-convert >/dev/null 2>&1; then
  echo "error: rsvg-convert not found. Install librsvg: 'brew install librsvg' (macOS)," \
    "'sudo apt install librsvg2-bin' (Debian/Ubuntu)." >&2
  exit 1
fi
if command -v magick >/dev/null 2>&1; then
  im=magick
elif command -v convert >/dev/null 2>&1; then
  im=convert
else
  echo "error: ImageMagick not found. Install it: 'brew install imagemagick' (macOS)," \
    "'sudo apt install imagemagick' (Debian/Ubuntu)." >&2
  exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# The flat icons are the full icon clipped to a rounded square with a transparent outside. The
# corner radius is 22.5% of the side, close to Apple's app icon corner.
cat >"$tmp/mask.svg" <<'EOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" rx="230" fill="#fff"/></svg>
EOF

# render_rounded SIZE OUT
render_rounded() {
  rsvg-convert -w "$1" -h "$1" "$icon_svg" -o "$tmp/icon.png"
  rsvg-convert -w "$1" -h "$1" "$tmp/mask.svg" -o "$tmp/mask.png"
  # The icon renders fully opaque, so it needs an alpha channel before the mask can cut into it.
  # -strip drops the timestamp chunks that would make every run differ.
  "$im" "$tmp/icon.png" -alpha set "$tmp/mask.png" -compose DstIn -composite -strip "PNG32:$2"
  echo "$2 (${1}x${1})"
}

# Android legacy launcher icons for API < 26; API 26+ uses the adaptive icon in mipmap-anydpi-v26.
render_rounded 48 "$android_res/mipmap-mdpi/ic_launcher.png"
render_rounded 72 "$android_res/mipmap-hdpi/ic_launcher.png"
render_rounded 96 "$android_res/mipmap-xhdpi/ic_launcher.png"
render_rounded 144 "$android_res/mipmap-xxhdpi/ic_launcher.png"
render_rounded 192 "$android_res/mipmap-xxxhdpi/ic_launcher.png"

# Android adaptive icon layers. The glyph's 1024 canvas maps onto the 72dp visible area of the
# 108dp layer (a 1536 viewport with the glyph offset by 256), so the π takes the same share of the
# icon as on the other platforms. Gradient coordinates stay in the glyph's own space.
glyph_path=$(sed -n 's/.* d="\([^"]*\)".*/\1/p' "$glyph_svg")
svg_attr() { grep -o " $1=\"[^\"]*\"" "$glyph_svg" | cut -d'"' -f2 || true; }
x1=$(svg_attr x1) y1=$(svg_attr y1) x2=$(svg_attr x2) y2=$(svg_attr y2)
stops=$(svg_attr stop-color)
start_color=$(sed -n 1p <<<"$stops")
end_color=$(sed -n 2p <<<"$stops")
if [[ $(grep -o '<path' "$glyph_svg" | wc -l) -ne 1 || -z $glyph_path || -z $x1 || -z $y1 ||
  -z $x2 || -z $y2 || $(wc -l <<<"$stops") -ne 2 ]]; then
  echo "error: $glyph_svg must hold one path filled with a two-stop linear gradient" >&2
  exit 1
fi

cat >"$android_res/drawable/ic_launcher_foreground.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icons.sh from $glyph_svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="1536"
    android:viewportHeight="1536">
    <group android:translateX="256" android:translateY="256">
        <path android:pathData="$glyph_path">
            <aapt:attr name="android:fillColor">
                <gradient
                    android:type="linear"
                    android:startX="$x1"
                    android:startY="$y1"
                    android:endX="$x2"
                    android:endY="$y2">
                    <item android:offset="0" android:color="$start_color" />
                    <item android:offset="1" android:color="$end_color" />
                </gradient>
            </aapt:attr>
        </path>
    </group>
</vector>
EOF
echo "$android_res/drawable/ic_launcher_foreground.xml"

cat >"$android_res/drawable/ic_launcher_monochrome.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icons.sh from $glyph_svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="1536"
    android:viewportHeight="1536">
    <group android:translateX="256" android:translateY="256">
        <path
            android:fillColor="#FFFFFF"
            android:pathData="$glyph_path" />
    </group>
</vector>
EOF
echo "$android_res/drawable/ic_launcher_monochrome.xml"

# Android notification icon (push): the glyph alone in white, cropped to fill the 24dp status bar icon inside
# Material's 2dp margin. The glyph's bounds are centred on the canvas and about 488 units wide.
cat >"$android_res/drawable/ic_notification.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icons.sh from $glyph_svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="584"
    android:viewportHeight="584">
    <group android:translateX="-220" android:translateY="-220">
        <path
            android:fillColor="#FFFFFF"
            android:pathData="$glyph_path" />
    </group>
</vector>
EOF
echo "$android_res/drawable/ic_notification.xml"

# Windows executable icon.
ico_pngs=()
for size in 16 20 24 32 40 48 64 256; do
  render_rounded "$size" "$tmp/ico-$size.png" >/dev/null
  ico_pngs+=("$tmp/ico-$size.png")
done
# Store the 256 px entry PNG-compressed, as Windows expects, instead of a 270 KB bitmap.
"$im" "${ico_pngs[@]}" -strip -define icon:png-compression-size=256 windows/runner/resources/app_icon.ico
echo "windows/runner/resources/app_icon.ico (16, 20, 24, 32, 40, 48, 64, 256)"

# Microsoft Store (MSIX) assets, the names windows/build-msix.ps1's manifest and its resource index look
# up. The tiles, the store logo and the plain target sizes are the full icon, full-bleed: the square is
# its own plate, so the manifest's transparent BackgroundColor never shows. The wide tile and the splash
# screen extend that square with its own corner colour.
msix=windows/msix/assets
rm -f "$msix"/*.png
mkdir -p "$msix"
# render_msix SIZE OUT [WIDTHxHEIGHT]
render_msix() {
  rsvg-convert -w "$1" -h "$1" "$icon_svg" -o "$tmp/msix.png"
  local canvas=${3:-${1}x${1}}
  "$im" "$tmp/msix.png" -background "$("$im" "$tmp/msix.png" -format '%[pixel:p{0,0}]' info:)" \
    -gravity center -extent "$canvas" -strip "PNG32:$msix/$2"
  echo "$msix/$2 ($canvas)"
}
render_msix 44 Square44x44Logo.png
render_msix 88 Square44x44Logo.scale-200.png
render_msix 150 Square150x150Logo.png
render_msix 300 Square150x150Logo.scale-200.png
render_msix 310 Square310x310Logo.png
render_msix 150 Wide310x150Logo.png 310x150
render_msix 50 StoreLogo.png
render_msix 300 SplashScreen.png 620x300
# The taskbar, Start and the app list use the unplated target sizes, dark and light theme alike: the π
# alone on transparency, trimmed and scaled to fill the canvas bar a 1/16 margin on each side, as a
# Win32 icon fills its own. Without them Windows shrinks the plated icon onto a system backplate.
rsvg-convert -w 2048 -h 2048 "$glyph_svg" -o "$tmp/msix-glyph.png"
for size in 16 24 32 48 256; do
  render_msix "$size" "Square44x44Logo.targetsize-$size.png"
  inner=$((size * 7 / 8))
  for form in unplated lightunplated; do
    name=Square44x44Logo.targetsize-${size}_altform-$form.png
    "$im" "$tmp/msix-glyph.png" -trim +repage -resize "${inner}x${inner}" -background none -gravity center \
      -extent "${size}x${size}" -strip "PNG32:$msix/$name"
    echo "$msix/$name (glyph, ${size}x${size})"
  done
done

# Linux window icon, installed into the bundle's data directory by linux/CMakeLists.txt.
render_rounded 256 linux/ompanion.png

# README header logo: the π alone on a transparent background, trimmed to its bounds so it lines up
# with the heading text. Rendered large, then scaled down, for smooth edges at the 24 px display size.
rsvg-convert -w 2048 -h 2048 "$glyph_svg" -o "$tmp/glyph.png"
"$im" "$tmp/glyph.png" -trim +repage -resize x256 -strip "PNG32:assets/ompanion.png"
echo "assets/ompanion.png (glyph, 256 px tall)"

# The Icon Composer bundles' single layer (icon.json sets fill, glass and shadow).
for bundle in macos/ompanion.icon ios/ompanion.icon; do
  cp "$glyph_svg" "$bundle/Assets/ompanion_glyph.svg"
  echo "$bundle/Assets/ompanion_glyph.svg"
done
